apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "books-api.fullname" . }}
  labels:
    {{- include "books-api.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "books-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "books-api.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.api.image.name }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.api.image.port }}
              protocol: TCP
