version: '3.7'

services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data 
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment: 
    - POSTGRES_USER=me
    - POSTGRES_PASSWORD=senha123
    - POSTGRES_DB=api
    - POSTGRES_PORT=5432
    - POSTGRES_HOST=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - helm
    
  node-helm:
    container_name: node-helm
    build:
      context: . # usado para definir onde está o arquivo Dockerfile, se não estivesse no meu nível, era necessário para o path
    ports:
      - 3000:3000
    environment:
      - POSTGRES_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - helm

networks:
  helm:
    name: helm
    external: true
    driver: bridge

volumes:
  pgdata:
